import fs from 'fs';
import path from 'path';

function convertToMinifiedBase64(filePath: string, mimeType: string): string {
  try {
    const absolutePath = path.resolve(filePath);
    if (!fs.existsSync(absolutePath)) {
      console.warn(`File not found: ${filePath}`);
      return '';
    }
    
    const fileBuffer = fs.readFileSync(absolutePath);
    return `data:${mimeType};base64,${fileBuffer.toString('base64')}`;
  } catch (error) {
    console.error(`Error converting ${filePath} to base64:`, error);
    return '';
  }
}

async function run() {
  console.log('Generating base64 PNG/JPG logos directly from public assets...');
  
  // Directly load native PNG for Infinitium
  const logoBase64 = convertToMinifiedBase64('public/logo.png', 'image/png');
  
  // Directly load native JPG for ARSD
  const arsdLogoBase64 = convertToMinifiedBase64('public/arsd_logo.jpg', 'image/jpeg');

  if (!logoBase64 || !arsdLogoBase64) {
    console.error('Error: Could not convert logos successfully.');
    process.exit(1);
  }

  const content = `// This file is auto-generated by scripts/generate-base64.ts
// Do not edit this file directly.

export const INFINITIUM_LOGO_BASE64 = ${JSON.stringify(logoBase64)};
export const ARSD_LOGO_BASE64 = ${JSON.stringify(arsdLogoBase64)};
`;

  fs.mkdirSync('src/assets', { recursive: true });
  fs.writeFileSync('src/assets/logoBase64.ts', content, 'utf8');
  console.log('Successfully generated src/assets/logoBase64.ts using direct PNG and JPG assets!');
}

run().catch(err => {
  console.error('Failed to run base64 generation:', err);
  process.exit(1);
});
